[package]
name = "arena"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.1.3", features = ["full", "node-bindings"] }
tokio = { version = "1.36.0", features = ["full"] }
revm = "10.0.0"
crossbeam-channel = "0.5"
alloy-sol-types = "0.7.6"
hyper = { version = "0.14", features = ["client", "http1", "tcp"] }

[lib]
doctest = false
