[package]
name = "arena"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.2.1", features = ["full"] }
rand = "0.8.5"
rand_distr = "0.4.3"
tokio = { version = "1.39.2", features = ["macros"] }
