[package]
name = "arena"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.2.1", features = ["full", "node-bindings"] }
alloy-sol-macro = "0.7.7"
alloy-sol-types = "0.7.7"
rand = "0.8.5"
rand_distr = "0.4.3"
tokio = { version = "1.39.2", features = ["macros"] }
