[package]
name = "arena-core"
description = "Robust simulation toolkit for Uniswap v4"
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.1.3", features = ["rlp", "node-bindings", "sol-types", "contract", "transports", "transport-http"] }
tokio = { version = "1.36.0", features = ["full"] }
revm = "10.0.0"
octane = { git = "https://github.com/arena-rs/octane" }
crossbeam-channel = "0.5"
alloy-sol-types = "0.7.6"
hyper = { version = "0.14", features = ["client", "http1", "tcp"] }
serde = "1.0.204"
async-trait = "0.1.81"
anyhow = "1.0.86"
tracing = "0.1.40"
env_logger = "0.11.3"
alloy-transport-http = "0.1"
serde_json = "1.0.120"
futures = "0.3.30"
rand = "0.8.5"
rand_distr = "0.4.3"
bytes = "1.6.1"

[lib]
doctest = false

[profile.test]
incremental = true
